from __future__ import annotations

from fastapi import FastAPI
from fastapi.responses import HTMLResponse


DASHBOARD_HTML = r"""
<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>BTC 5m Paper HF</title><style>
:root{color-scheme:dark;--bg:#07111f;--panel:#10213a;--line:#2a405e;--text:#eef5ff;--muted:#9fb2cc;--yes:#2ed573;--no:#ff6b6b;--wait:#f6c344}*{box-sizing:border-box}body{margin:0;background:#07111f;color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:980px;margin:auto;padding:16px 14px 34px}.top{display:flex;justify-content:space-between;gap:12px}.title{font-size:24px;font-weight:900}.sub,.muted{color:var(--muted)}.pill{border:1px solid var(--line);padding:8px 12px;border-radius:999px;font-weight:800}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:12px;margin-top:14px}.card{grid-column:span 12;background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:14px}.mini{grid-column:span 6}.third{grid-column:span 4}.quarter{grid-column:span 3}.label{color:var(--muted);font-size:13px}.value{font-size:30px;font-weight:900}.small{font-size:21px;font-weight:850}.row{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid rgba(159,178,204,.16)}.row:last-child{border-bottom:0}.mono{font-family:ui-monospace,monospace;font-size:12px;overflow-wrap:anywhere}.yes{color:var(--yes)}.no{color:var(--no)}.wait{color:var(--wait)}a{color:#b9e6ff;text-decoration:none;margin-right:10px}@media(max-width:720px){.mini,.third,.quarter{grid-column:span 12}}
</style></head><body><main class="wrap"><header class="top"><div><div class="title">BTC 5 分鐘預測市場 · Paper HF</div><div class="sub">YES 上漲 · NO 下跌 · WAIT 不下注 · 同輪可分批模擬下單</div></div><div id="pill" class="pill">LOADING</div></header><section class="grid">
<article class="card mini"><div class="label">目前 AI 方向</div><div id="direction" class="value wait">WAIT</div><div id="reason" class="muted">等待資料</div></article><article class="card mini"><div class="label">距離本輪結束</div><div id="countdown" class="value">--:--</div><div class="muted">最後 15 秒停止加倉</div></article>
<article class="card third"><div class="label">上漲機率</div><div id="probability" class="small">—</div></article><article class="card third"><div class="label">信心</div><div id="confidence" class="small">—</div></article><article class="card third"><div class="label">本輪微單</div><div id="orderCount" class="small">0 / 20</div></article>
<article class="card quarter"><div class="label">微單勝率</div><div id="winRate" class="small">0.00%</div></article><article class="card quarter"><div class="label">勝 / 負 / 平</div><div id="record" class="small">0 / 0 / 0</div></article><article class="card quarter"><div class="label">已實現 PnL</div><div id="pnl" class="small">$0.0000</div></article><article class="card quarter"><div class="label">本輪本金</div><div id="roundNotional" class="small">$0.00 / $25</div></article>
<article class="card mini"><h3>限制</h3><div class="row"><span>每秒最多</span><strong>2 筆</strong></div><div class="row"><span>每輪最多</span><strong>20 筆</strong></div><div class="row"><span>每輪本金上限</span><strong>$25</strong></div><div class="row"><span>同方向冷卻</span><strong>500 ms</strong></div><div class="row"><span>反轉冷卻</span><strong>3 秒</strong></div><div class="row"><span>真實下單</span><strong class="no">OFF</strong></div></article>
<article class="card mini"><h3>目前市場</h3><div class="row"><span>狀態</span><strong id="marketStatus">—</strong></div><div class="row"><span>Slug</span><strong id="slug" class="mono">—</strong></div><div class="row"><span>YES Ask</span><strong id="yesAsk">—</strong></div><div class="row"><span>NO Ask</span><strong id="noAsk">—</strong></div></article>
<article class="card"><h3>本輪微單</h3><pre id="orders" class="mono">[]</pre><div><a href="/mode">/mode</a><a href="/status">/status</a><a href="/paper/winrate">/paper/winrate</a><a href="/paper/rounds">/paper/rounds</a><a href="/healthz">/healthz</a></div></article>
</section></main><script>
const $=x=>document.getElementById(x),pct=x=>Number.isFinite(Number(x))?`${(Number(x)*100).toFixed(2)}%`:'—',money=x=>`$${Number(x||0).toFixed(2)}`,contract=x=>Number.isFinite(Number(x))?Number(x).toFixed(4):'—';function cls(d){return d==='YES'?'yes':d==='NO'?'no':'wait'}function cd(c){let s=Number(c?.interval_start||0);if(!s){const m=String(c?.slug||'').match(/(\d{10})$/);if(m)s=Number(m[1])}if(!s)return'--:--';const r=Math.max(0,s+300-Math.floor(Date.now()/1000));return`${String(Math.floor(r/60)).padStart(2,'0')}:${String(r%60).padStart(2,'0')}`}async function refresh(){try{const s=await fetch('/status',{cache:'no-store'}).then(r=>r.json()),p=s.paper||{},sum=p.summary||{},r=p.current_round||{},m=s.market||{},cur=m.current||{},d=r.direction||s.ai?.direction||'WAIT';$('direction').textContent=d;$('direction').className=`value ${cls(d)}`;$('reason').textContent=r.reason||s.ai?.reason||'等待資料';$('countdown').textContent=cd(cur);$('probability').textContent=pct(s.ai?.probability_up);$('confidence').textContent=pct(s.ai?.confidence);$('orderCount').textContent=`${r.order_count||0} / 20`;$('winRate').textContent=pct(sum.win_rate||0);$('record').textContent=`${sum.wins||0} / ${sum.losses||0} / ${sum.flat||0}`;$('pnl').textContent=money(sum.realized_pnl);$('roundNotional').textContent=`${money(r.total_notional_usd)} / $25`;$('marketStatus').textContent=m.discovery_status||'—';$('slug').textContent=cur.slug||'—';$('yesAsk').textContent=contract(m.yes_ask);$('noAsk').textContent=contract(m.no_ask);$('orders').textContent=JSON.stringify((r.orders||[]).slice(-10),null,2);$('pill').textContent=m.discovery_status==='ready'?'SYSTEM ACTIVE':'WAITING'}catch(e){$('pill').textContent='OFFLINE'}}refresh();setInterval(refresh,1000)
</script></body></html>
"""


def register_btc5m_hf_ui(app: FastAPI) -> None:
    @app.get("/ui", response_class=HTMLResponse)
    async def ui() -> HTMLResponse:
        return HTMLResponse(DASHBOARD_HTML)
